apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: accounts-service-hpa
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: accounts-service
  targetCPUUtilizationPercentage: 50
