apiVersion: v1
kind: Secret
metadata:
  name: cosmosdb-secret
type: Opaque
data:
  ENTRYPOINT: <entrypoint here in base64>
  PRIMARYKEY: <primarykey here in base64>
  DATABASE: <database here in base64>
