apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
spec:
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - image: coalitionbank.azurecr.io/api-service:latest
          name: api-service
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: USERS_SERVICE_URI
              value: http://users-service
            - name: TRANSACTIONS_SERVICE_URI
              value: http://transactions-service
            - name: ACCOUNTS_SERVICE_URI
              value: http://accounts-service
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1024Mi
          ports:
            - containerPort: 80
              name: http
