apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions-service
spec:
  selector:
    matchLabels:
      app: transactions-service
  template:
    metadata:
      labels:
        app: transactions-service
    spec:
      containers:
        - image: coalitionbank.azurecr.io/transactions-service:latest
          name: transactions-service
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 80
              name: http