apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions-service
spec:
  selector:
    matchLabels:
      app: transactions-service
  template:
    metadata:
      labels:
        app: transactions-service
    spec:
      containers:
        - image: coalitionbank.azurecr.io/transactions-service:latest
          name: transactions-service
          env:
            - name: COSMOS_ENTRYPOINT
              valueFrom:
                secretKeyRef:
                  name: cosmosdb-secret
                  key: ENTRYPOINT
            - name: COSMOS_PRIMARYKEY
              valueFrom:
                secretKeyRef:
                  name: cosmosdb-secret
                  key: PRIMARYKEY
            - name: COSMOS_DATABASE
              valueFrom:
                secretKeyRef:
                  name: cosmosdb-secret
                  key: DATABASE
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1024Mi
          ports:
            - containerPort: 80
              name: http
