apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
spec:
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - image: coalitionbank.azurecr.io/users-service:latest
          name: users-service
          env:
            - name: COSMOS_ENTRYPOINT
              valueFrom:
                secretKeyRef:
                  name: cosmosdb-secret
                  key: ENTRYPOINT
            - name: COSMOS_PRIMARYKEY
              valueFrom:
                secretKeyRef:
                  name: cosmosdb-secret
                  key: PRIMARYKEY
            - name: COSMOS_DATABASE
              valueFrom:
                secretKeyRef:
                  name: cosmosdb-secret
                  key: DATABASE
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 512Mi
          ports:
            - containerPort: 80
              name: http
