name: Build and Publish Accounts Service.

on:
  release:
    types: [published]

env:
  DOCKERFILE_LOCATION: CoalitionBank.Services.Accounts/Dockerfile
  CONTAINER_NAME: accounts-service

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      uses: docker/login-action@v1.10.0
      with:
        registry: ${{ secrets.CONTAINER_REGISTRY_NAME }}
        username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
    - name: Build and Push container to registry
      env:
        CONTAINER_TAG: ${{ secrets.CONTAINER_REGISTRY_NAME }}/${{ env.CONTAINER_NAME }}
        CONTAINER_TAG_SHA: ${{ secrets.CONTAINER_REGISTRY_NAME }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
        CONTAINER_TAG_LATEST: ${{ secrets.CONTAINER_REGISTRY_NAME }}/${{ env.CONTAINER_NAME }}:latest
      run: |
        docker build --file=${{ env.DOCKERFILE_LOCATION }} -t ${{ env.CONTAINER_TAG_SHA }} -t ${{ env.CONTAINER_TAG_LATEST }} .
        docker push ${{ env.CONTAINER_TAG }} --all-tags
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: production
        resource-group: CoalitionBank
    - uses: azure/k8s-create-secret@v1
      with:
        container-registry-url: ${{ secrets.CONTAINER_REGISTRY_NAME }}
        container-registry-username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
        container-registry-password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
        secret-name: acr-secret
        namespace: default
        force: true
    - uses: azure/k8s-deploy@v1
      with:
        manifests: |
          kubernetes/deployments/${{ env.CONTAINER_NAME }}.yml
          kubernetes/services/${{ env.CONTAINER_NAME }}.yml
        images: |
          ${{ secrets.CONTAINER_REGISTRY_NAME }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
        imagepullsecrets: |
          acr-secret
        namespace: default
